In [3]:
import pandas as pd
import numpy as np

In [7]:
s1 = pd.Series([1,2,3])
s2 = pd.Series(['A','B','C'])

In [8]:
s1

0    1
1    2
2    3
dtype: int64

In [9]:
s2

0    A
1    B
2    C
dtype: object

In [11]:
s3 = pd.Series(np.arange(200))
s3

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int32

In [13]:
pd.Series([1,2,3],[100,200,300])

100    1
200    2
300    3
dtype: int64

In [14]:
pd.Series([1,2,3],['A','M','D'])

A    1
M    2
D    3
dtype: int64

In [17]:
# data, index, 데이터 타입 명시
s6 = pd.Series(np.arange(5), np.arange(100,105), dtype=np.int32)
s6

100    0
101    1
102    2
103    3
104    4
dtype: int32

In [18]:
s6.index

Int64Index([100, 101, 102, 103, 104], dtype='int64')

In [19]:
s6.values

array([0, 1, 2, 3, 4])

In [20]:
s6[104] =70

In [21]:
s6.values

array([ 0,  1,  2,  3, 70])

In [23]:
s6[107] =90
s6

100     0
101     1
102     2
103     3
104    70
107    90
dtype: int64

In [24]:
s = pd.Series(np.arange(10))

In [25]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [26]:
len(s)

10

In [27]:
size(s)

NameError: name 'size' is not defined

In [28]:
s.size

10

In [29]:
s.shape

(10,)

In [30]:
s.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
s.count() # NaN 제외

10

In [40]:
n = np.array([2,2,2,2, np.NaN])
n.mean()

nan

In [37]:
print(n)

10
